services:
  web:
    build:
      context: ./docker-timesheets
      dockerfile: Dockerfile
    entrypoint: /usr/src/docker-timesheets/entrypoint.sh
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app  # Live code reload
    command: python manage.py runserver 0.0.0.0:8000

