services:
  web:
    build:
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "${DOCKER_WEB_PORT:-8000}:8000"  # Configurable port
    volumes:
      - ./nginx-ssl/rapoarteactivitate.bucegipark.ro.crt:/etc/nginx/certs/rapoarteactivitate.bucegipark.ro.crt:ro
      - ./nginx-ssl/rapoarteactivitate.bucegipark.ro.key:/etc/nginx/certs/rapoarteactivitate.bucegipark.ro.key:ro
    command: >
      gunicorn timesheets_main.wsgi:application
      --bind 0.0.0.0:8000
      --workers $${GUNICORN_WORKERS:-4}  # Fallback to 4 workers
      --threads $${GUNICORN_THREADS:-2}  # Fallback to 2 threads
      --timeout 30
      --max-requests 1000
      --max-requests-jitter 50
      --worker-class gthread
      --access-logfile -
      --error-logfile -
      --log-level info
    deploy:
      resources:
        limits:
          cpus: '2'  # CPU limits
          memory: 2G  # Memory limits
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /srv/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx-ssl/rapoarteactivitate.bucegipark.ro.crt:/etc/nginx/certs/rapoarteactivitate.bucegipark.ro.crt:ro
      - ./nginx-ssl/rapoarteactivitate.bucegipark.ro.key:/etc/nginx/certs/rapoarteactivitate.bucegipark.ro.key:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
    depends_on:
      - web
