version: '3.8'

services:
  web:
    build:
      context: ./docker-timesheets
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timesheetsadmin -h db -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:
  media_volume: