###########
# BUILDER #
###########

# Use Python 3.12 for both stages
FROM python:3.12-slim-bookworm as builder

# Set work directory
WORKDIR /usr/src/docker-timesheets

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install linting and dependencies
RUN pip install --upgrade pip
RUN pip install flake8==6.0.0
COPY . .
RUN flake8 --ignore=E501,F401,F403,F405,F841 .

# Create wheels
COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/docker-timesheets/wheels -r requirements.txt

#########
# FINAL #
#########

FROM python:3.12-slim-bookworm

# Create and configure app user
RUN addgroup --system daniel && \
    adduser --system --ingroup daniel daniel

# Set up directories
ENV APP_HOME=/home/docker-timesheets/web
RUN mkdir -p $APP_HOME/staticfiles $APP_HOME/mediafiles
WORKDIR $APP_HOME

# Copy from builder
COPY --from=builder /usr/src/docker-timesheets/wheels /wheels
COPY --from=builder /usr/src/docker-timesheets/requirements.txt .

# Install dependencies
RUN pip install --no-cache /wheels/* && \
    rm -rf /wheels

# Copy project files
COPY . .

# Set permissions
RUN chown -R daniel:daniel $APP_HOME && \
    chmod -R 755 $APP_HOME/staticfiles $APP_HOME/mediafiles

# Entrypoint setup
COPY ./entrypoint.prod.sh .
RUN sed -i 's/\r$//g' entrypoint.prod.sh && \
    chmod +x entrypoint.prod.sh

# Switch to non-root user
USER daniel

# Runtime configuration
ENTRYPOINT ["/home/docker-timesheets/web/entrypoint.prod.sh"]
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "docker_timesheets.wsgi:application"]